version: '3'

services:
  pokedexapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: portafolio-nest
    container_name: portafolio-nest
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
      JWT_SECRET: ${JWT_SECRET}

    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    container_name: portafolio-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: portafolio-db
    volumes:
      - ./mongo:/data/db

 

